@startuml

skinparam SequenceMessageAlignment center
group user register account
user -> fxui: Create new user
fxui -> core: insertUser()
core -> users.json: validate
users.json --> core: user not in json 
core -> users.json: user added
end
group user logs in
user -> fxui: User log in
fxui -> core: getUsers()
core -> users.json:validate login
users.json --> core: user exist
core --> fxui: getActiveUser()
fxui --> user: initialize()
end
group initializeTableview()
fxui --> fxui: initializeTableview
note left 
Methods initialized:
initialize()
addContact(activeUser, newUser)
end note
fxui -> core: getRelevantMap()
core -> users.json: read from json
users.json --> core: return users.json
core -> fxui: deserialize json
fxui -> user: display closecontacts
end
group user add closecontacts
user -> fxui: user logs in
fxui -> core: addContact(email)
core -> users.json: validate that user exist
users.json --> core: user exist
core -> users.json: user added
users.json --> core: deserialize json
core --> fxui: getRelevantMap()
fxui --> user: tableview updates
end

@enduml